Add arena background color variable
SylviBlossom/kristal pull request #1
Opened 2021-11-04 23:15 UTC by l-Luna

Adds a bgColor field to arenas that allows specifying their background colour.

2021-11-04 23:22 UTC, NyakoFox requested changes
Looks good, I just have a few nitpicks

2021-11-04 23:22 UTC, NyakoFox commented on mods/example/scripts/battles/waves/vironeedle.lua
> +    Game.battle.arena.bgColor = {0.2, 0.2, 0}
You should probably revert your test changes here ^^;;

2021-11-04 23:22 UTC, NyakoFox commented on src/object/game/arenasprite.lua
> +        love.graphics.setColor(self.arena.bgColor[1], self.arena.bgColor[2], self.arena.bgColor[3])
This function takes a table, so you can just do `love.graphics.setColor(self.arena.bgColor)`. That'd also allow it to support alpha, which this doesn't do

2021-11-04 23:22 UTC, NyakoFox commented on src/object/game/arena.lua
> +    self.bgColor = {0, 0, 0}
The naming scheme for variables is `snake_case`, so `self.bg_color` is better here. Also, all objects have `setColor` and `getColor`, so I'd recommend implementing `setBackgroundColor` and `getBackgroundColor` for the arena.

2021-11-05 08:31 UTC, l-Luna commented
should all be fixed

2021-11-05 16:41 UTC, NyakoFox commented
LGTM, thanks!

2021-11-05 16:41 UTC, merged